 CLASS zcl_disc_price_test_class DEFINITION
  PUBLIC FINAL
  CREATE PUBLIC
  FOR TESTING.

   PUBLIC SECTION.
   PROTECTED SECTION.
   PRIVATE SECTION.
 ENDCLASS.

 CLASS zcl_disc_price_test_class IMPLEMENTATION.
 ENDCLASS.
